language: node_js
node_js:
  - 16
branches:
  only:
    - master
before_install:
  - echo "//familysearch.jfrog.io/artifactory/api/npm/fs-npm-prod-virtual/:_authToken=${NPM_PUBLISH_TOKEN}" >> ~/.npmrc
  - echo "@fs:registry=https://familysearch.jfrog.io/artifactory/api/npm/fs-npm-prod-virtual/" >> ~/.npmrc
script: echo "no tests to run at this time"
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run publish
    on:
      branch: master
